// Generated by gencpp from file exploration/Trigger.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_TRIGGER_H
#define EXPLORATION_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <exploration/TriggerRequest.h>
#include <exploration/TriggerResponse.h>


namespace exploration
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration::Trigger > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::exploration::Trigger&) { return value(); }
};

template<>
struct DataType< ::exploration::Trigger > {
  static const char* value()
  {
    return "exploration/Trigger";
  }

  static const char* value(const ::exploration::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::exploration::TriggerRequest> should match
// service_traits::MD5Sum< ::exploration::Trigger >
template<>
struct MD5Sum< ::exploration::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::Trigger >::value();
  }
  static const char* value(const ::exploration::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::TriggerRequest> should match
// service_traits::DataType< ::exploration::Trigger >
template<>
struct DataType< ::exploration::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::exploration::Trigger >::value();
  }
  static const char* value(const ::exploration::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration::TriggerResponse> should match
// service_traits::MD5Sum< ::exploration::Trigger >
template<>
struct MD5Sum< ::exploration::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::Trigger >::value();
  }
  static const char* value(const ::exploration::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::TriggerResponse> should match
// service_traits::DataType< ::exploration::Trigger >
template<>
struct DataType< ::exploration::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::exploration::Trigger >::value();
  }
  static const char* value(const ::exploration::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION_MESSAGE_TRIGGER_H
